server:
  port: 9000

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/pet?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jwt:
    secret:
      key: aWmOUeJL6T/E6GuAIqZTpEnStxIbc2nOH0BSusakjdhiuqgwdubkjvaabkjabskbkaEZgVbw= # 다시 설정하기

  data:
    redis:
      host: localhost
      port: 6379